### ISSUE TITLE
Erro nos comandos -f --formation_url e --formation

### ISSUE THREAD

**Issue by luccaaltomani** [gustavopedroni/alura-downloader#4]
![image](https://user-images.githubusercontent.com/70582824/153109307-23f96ec4-be9c-419e-aa19-5b0d0a385781.png)

Mesmo erro se replica para os citados no título.

**Comment by gustavopedroni** [comment]
Você precisa rodar o comando dessa forma:
`python main.py formation https://cursos.alura.com.br/formacao-django --output D:/Alura/Django`

Eu recomendaria você utilizar com o Docker
